FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install nltk pythainlp
# RUN pip3 install --upgrade pythainlp

RUN pip3 install --user -U nltk
COPY . .


EXPOSE 5000

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0","--port=5000"]
